config/routes.rb
Rails.application.routes.draw do
  resources :checklists do
    resources :checklist_items do
      member do
        post :completed
        post :uncompleted
      end
    end
  end
  resources :valuation_url_comments

  get 'members/index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  resources :pre_launch_registrations, only: [:new, :create] do
    get :success, on: :collection
  end

  resources :organizations, only: [:show, :edit, :update] do
    resources :customers, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :bulk_archive, on: :collection
    end

    resources :appraisals, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :clone, on: :member
      get :sales_sheet, on: :member
      get :appraisal_sheet, on: :member
      put :bulk_archive, on: :collection
      get :remove_entry, on: :member
      get :history, on: :member
      post :comment, on: :member
      get :valuations, on: :member
      post :pin, on: :member
      post :unpin, on: :member
      get :reveal_comments, on: :member
      get :hide_comments, on: :member
      put :valuation, on: :member

      resources :discussions do
        resources :discussion_comments
      end

      resources :valuation_urls
    end

    resources :members, only: [:index, :show, :update] do
      post :invite_user, on: :collection
      get :reset_password, on: :member
      get :resend_invitation, on: :member
    end
  end

  resources :members, only: [] do
    get :accept_invitation, on: :collection
  end

  resources :attachments

  resources :reports do
    get :inventory_commitments, on: :collection
  end

  resources :print_templates

  resources :appraisal_categories, only: [:show]

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]

      resources :appraisals, only: [:index] do
        resources :appraisal_categories, only: [:show]
      end

      resources :organizations, only: [:index] do
        resources :appraisals, only: [:create, :show, :update]
        resources :customers, only: [:create, :show, :update]
      end
    end
  end
end

app/controllers/discussion_comments_controller.rb
class DiscussionCommentsController < ApplicationController
  def new
    @comment = Comment.new
    @discussion = Discussion.find(params[:id])
    @appraisal = @discussion.appraisal
    @organization = @appraisal.organization

    authorize @comment
  end

  def create
    @discussion = Discussion.find(params[:discussion_id])
    @comment = Comment.new(comment: discussion_comment_params[:comment], commentable_id: params[:discussion_id], commentable_type: "Discussion", user_id: current_user.id)
    @comment.save

    authorize @comment
  end

  def show
    @comments = Comment
      .where(commentable_type: "Discussion", commentable_id: params[:id])
    @discussion = Discussion.find(params[:id])
    @appraisal = @discussion.appraisal

    authorize @comments
  end

  private

  def discussion_comment_params
    params
      .require(:comment)
      .permit(:comment)
  end
end

app/helpers/discussion_comments_helper.rb
module DiscussionCommentsHelper
end

app/views/discussion_comments/_add_discussion_comment_modal.html.haml
.modal#discussion-comment-creation-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: { dismiss: "modal" }} &times;
        %h4.modal-title Add Your Comment
      .modal-body
        = render "discussion_comment_form", discussion: @discussion, comment: @comment, appraisal: @appraisal, organization: @organization

app/views/discussion_comments/_discussion_comment.html.haml
%tr
  %td.name= "#{comment.user.name}"
  %td.state-and-price
    %span.comment
      = "#{comment.comment}"
  %td.posted-time
    = comment.created_at.strftime("%b %d")

app/views/discussion_comments/_discussion_comment_form.html.haml
= simple_form_for comment, remote: true,
                  url: organization_appraisal_discussion_discussion_comments_path(organization, appraisal, discussion, format: :js) do |f|
  = f.input :comment

  .center-text
    = f.submit nil, class: "btn btn-primary",
             data: { disable_with: "Submitting ..." }

app/views/discussion_comments/_discussion_comments.html.haml
.row#discussion-comments-container
  %h2
    %span= @discussion.name
    = link_to "Add to this Discussion", new_organization_appraisal_discussion_discussion_comment_path(@appraisal.organization.id, @appraisal.id, discussion_id: @discussion.id, id: @discussion.id), remote: true, class: "btn btn-default add-discussion-comment-btn"
    = link_to "Back to Valuation Discussions", organization_appraisal_discussion_path(@appraisal.organization.id, @appraisal.id, id: @appraisal.id, format: :js), remote: true, class: "btn btn-default back-to-discussions-btn"
  - discussion_comments.each do |comment|
    %table#discussion-comments
      = render "discussion_comment", comment: comment

app/views/discussion_comments/create.js.erb
$modal = $("#discussion-comment-creation-modal");

<% if @comment.persisted? %>
    $modal.modal("hide");

  $div = $("#discussion-comments");
  $discussion = $("<%= j render "discussion_comments/discussion_comment", comment: @comment %>")

  $div.append($discussion);
<% else %>
    form = "<%= j render "discussion_comments/discussion_comment_form", comment: @comment, discussion: @discussion, appraisal: @discussion.appraisal, organization: @discussion.appraisal.organization %>";
  $modal.find(".modal-body").html(form);
<% end %>

app/views/discussion_comments/new.js.erb
$discussion_modal = $("<%= j render "discussion_comments/add_discussion_comment_modal" %>")
$("body").append($discussion_modal)

$modal = $("<%= j render 'discussion_comments/add_discussion_comment_modal' %>");

if ($("#discussion-comment-creation-modal").length > 0) {
    $("#discussion-comment-creation-modal").remove()
}

$("body").append($modal);

$('#discussion-comment-creation-modal').modal();

app/views/discussion_comments/show.js.erb
$discussion_comments = $("<%= j render "discussion_comments/discussion_comments", discussion_comments: @comments %>")
$("#discussions-container").replaceWith($discussion_comments)