config/routes.rb
Rails.application.routes.draw do
  resources :checklists do
    resources :checklist_items do
      member do
        post :completed
        post :uncompleted
      end
    end
  end
  resources :valuation_url_comments

  get 'members/index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  resources :pre_launch_registrations, only: [:new, :create] do
    get :success, on: :collection
  end

  resources :organizations, only: [:show, :edit, :update] do
    resources :customers, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :bulk_archive, on: :collection
    end

    resources :appraisals, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :clone, on: :member
      get :sales_sheet, on: :member
      get :appraisal_sheet, on: :member
      put :bulk_archive, on: :collection
      get :remove_entry, on: :member
      get :history, on: :member
      post :comment, on: :member
      get :valuations, on: :member
      post :pin, on: :member
      post :unpin, on: :member
      get :reveal_comments, on: :member
      get :hide_comments, on: :member
      put :valuation, on: :member

      resources :discussions do
        resources :discussion_comments
      end

      resources :valuation_urls
    end

    resources :members, only: [:index, :show, :update] do
      post :invite_user, on: :collection
      get :reset_password, on: :member
      get :resend_invitation, on: :member
    end
  end

  resources :members, only: [] do
    get :accept_invitation, on: :collection
  end

  resources :attachments

  resources :reports do
    get :inventory_commitments, on: :collection
  end

  resources :print_templates

  resources :appraisal_categories, only: [:show]

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]

      resources :appraisals, only: [:index] do
        resources :appraisal_categories, only: [:show]
      end

      resources :organizations, only: [:index] do
        resources :appraisals, only: [:create, :show, :update]
        resources :customers, only: [:create, :show, :update]
      end
    end
  end
end

app/models/valuation_url.rb
class ValuationUrl < ActiveRecord::Base
  acts_as_commentable
  belongs_to :appraisal
end

app/controllers/valuation_urls_controller.rb
class ValuationUrlsController < ApplicationController
  def create
    @valuation_url = ValuationUrl.new(
      valuation_url_params.merge({ user_id: current_user.id, appraisal_id: params[:appraisal_id] }))
    @valuation_url.save

    @appraisal = Appraisal.find(params[:appraisal_id])
    @organization = Organization.find(params[:organization_id])

    authorize @valuation_url
  end

  def show
    @appraisal = Appraisal.find(params[:appraisal_id])
    @organization = Organization.find(params[:organization_id])

    @valuation_urls = ValuationUrl
      .where(appraisal_id: @appraisal.id)
    @valuation_url = ValuationUrl.new

    authorize @valuation_url
  end

  private

  def valuation_url_params
    params
      .require(:valuation_url)
      .permit(:url, :year, :make, :model, :retail_value, :wholesale_value)
  end
end

app/helpers/valuation_urls_helper.rb
module ValuationUrlsHelper
end

app/views/valuation_urls/_add_valuations_url_modal.html.haml
.modal#valuation-urls-creation-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: { dismiss: "modal" }} &times;
        %h4.modal-title Add a URL
      .modal-body
        = render "valuation_urls/valuation_url_form", valuation_url: @valuation_url, appraisal: @appraisal, organization: @organization

app/views/valuation_urls/_url.html.haml
%tr
  %td.name= "#{discussion.comments.first.user.name}"
  %td.state-and-price
    %strong
      = link_to organization_appraisal_discussion_discussion_comment_path(@organization.id, @appraisal.id, discussion_id: discussion.id, id: discussion.id), remote: true, format: :js do
        = discussion.name
    %span.comment
      = "#{discussion.comments.first.comment}"
  %td.posted-time
    = discussion.comments.first.created_at.strftime("%b %d")

app/views/valuation_urls/_urls.html.haml
.row#valuation-urls-container
  %h2
    %span
      Valuation URLS
    = link_to "Create a new URL", "#valuation-urls-creation-modal", data: { toggle: "modal" }, class: "btn btn-default add-url-btn"
  %table#valuation-urls
    - @valuation_urls.each do |url|
      = render "valuation_urls/valuation_url", valuation_url: url

app/views/valuation_urls/_valuation_url.html.haml
%tr
  %td.name
    = link_to "#{truncate(valuation_url.url, length: 21)}", valuation_url.url, target: "_blank"
  %td.state-and-price
    %strong
      = "#{valuation_url.year} - #{valuation_url.make} - #{valuation_url.model} - #{number_to_currency(valuation_url.retail_value, precision: 0)} - #{number_to_currency(valuation_url.wholesale_value, precision: 0)}"
  %td.posted-time
    = link_to valuation_url_comment_path(valuation_url.id, format: :js), remote: true do
      Comments
      = fa_icon "fa-comments"

app/views/valuation_urls/_valuation_url_form.html.haml
= simple_form_for valuation_url, remote: true,
                  url: organization_appraisal_valuation_urls_path(organization, appraisal, format: :js) do |f|
  = f.input :url
  = f.input :year
  = f.input :make
  = f.input :model
  = f.input :retail_value
  = f.input :wholesale_value

  .center-text
    = f.submit nil, class: "btn btn-primary",
             data: { disable_with: "Submitting ..." }

app/views/valuation_urls/create.js.erb
$modal = $("#valuation-urls-creation-modal");

<% if @valuation_url.persisted? %>
  $modal.modal("hide");

  $div = $("#valuation-urls");
  $valuation_url = $("<%= j render "valuation_urls/valuation_url", valuation_url: @valuation_url %>")

  $div.append($valuation_url);
<% else %>
  form = "<%= j render "valuation_urls/valuation_url_form", valuation_url: @valuation_url, appraisal: @appraisal, organization: @organization %>";
  $modal.find(".modal-body").html(form);
<% end %>

app/views/valuation_urls/show.js.erb
$discussions = $("<%= j render "valuation_urls/urls", valuation_urls: @valuation_urls %>")
$("#valuation-url-comments-container").replaceWith($discussions)