config/routes.rb
Rails.application.routes.draw do
  resources :checklists do
    resources :checklist_items do
      member do
        post :completed
        post :uncompleted
      end
    end
  end
  resources :valuation_url_comments

  get 'members/index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  resources :pre_launch_registrations, only: [:new, :create] do
    get :success, on: :collection
  end

  resources :organizations, only: [:show, :edit, :update] do
    resources :customers, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :bulk_archive, on: :collection
    end

    resources :appraisals, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :clone, on: :member
      get :sales_sheet, on: :member
      get :appraisal_sheet, on: :member
      put :bulk_archive, on: :collection
      get :remove_entry, on: :member
      get :history, on: :member
      post :comment, on: :member
      get :valuations, on: :member
      post :pin, on: :member
      post :unpin, on: :member
      get :reveal_comments, on: :member
      get :hide_comments, on: :member
      put :valuation, on: :member

      resources :discussions do
        resources :discussion_comments
      end

      resources :valuation_urls
    end

    resources :members, only: [:index, :show, :update] do
      post :invite_user, on: :collection
      get :reset_password, on: :member
      get :resend_invitation, on: :member
    end
  end

  resources :members, only: [] do
    get :accept_invitation, on: :collection
  end

  resources :attachments

  resources :reports do
    get :inventory_commitments, on: :collection
  end

  resources :print_templates

  resources :appraisal_categories, only: [:show]

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]

      resources :appraisals, only: [:index] do
        resources :appraisal_categories, only: [:show]
      end

      resources :organizations, only: [:index] do
        resources :appraisals, only: [:create, :show, :update]
        resources :customers, only: [:create, :show, :update]
      end
    end
  end
end

app/models/organization.rb
class Organization < ActiveRecord::Base
  extend FriendlyId
  friendly_id :acronym, use: [:slugged, :finders]

  has_many :customers
  has_many :appraisals
  has_many :memberships
  has_many :users, through: :memberships
  has_and_belongs_to_many :appraisal_templates
  has_one :setting
  belongs_to :owner, foreign_key: 'owner_id', class_name: 'User'
  belongs_to :admin, foreign_key: 'admin_id', class_name: 'User'
  has_many :field_access_control
  has_many :appraisal_columns

  validates :name, presence: true
  validates :acronym, format: { with: /\A[A-Z]{3}\z/,
                                message: "Must be 3 capital letters"},
                      presence: true
  validates :owner, :admin, presence: true

  has_attached_file :map_image
  has_attached_file :company_logo
  
  accepts_nested_attributes_for :users

  validates_attachment_content_type :map_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :company_logo, :content_type => /\Aimage\/.*\Z/

  after_save :send_notification_to_admin

  def owner?(user)
    user == owner
  end

  def admin?(user)
    user == admin
  end

  def representatives
    rep_roles = Role.where(name: 'Rep').pluck(:id)
    users.joins(:memberships).where(memberships: { organization_id: id, role_id:  rep_roles }).distinct
  end

  def representatives?(user)
    membership = Membership.by_organization(id).by_user(user).representatives
    membership.present?
  end

  def member?(member)
    users.exists?(member) && !(admin?(member) || owner?(member))
  end

  def full_address
    "#{self.street_address}, #{self.city}, #{self.state} #{self.zipcode}"
  end

  def email_suffixes
    if email_suffix.present?
      email_suffix.delete(' ').split(',')
    else
      []
    end
  end

  def next_appraisal_number(increment: false)
    if increment
      self.increment!(:appraisal_sequence)
      number = self.appraisal_sequence
    else
      number = self.appraisal_sequence + 1
    end

    padded_number = sprintf("%06d", number)
    "#{acronym}-#{padded_number}"
  end

  def setting=(params)
    if self.setting.nil?
      params[:organization_id] = self.id
      Setting.create(params)
    else
      setting.update_attributes(params)
    end
  end

  def send_notification_to_admin
    MemberMailer.notify_news_of_being_org_admin(self).deliver if admin_id_changed?
    MemberMailer.notify_news_of_being_org_owner(self).deliver if owner_id_changed?
  end

  def template_fields_control
    TemplateField.where(id: FieldAccessControl.by_organization(self.id).map(&:template_field_id))
  end
  def organization_field_access
    FieldAccessControl.by_organization(self.id)
  end

  def is_field_disabled(field_name, role, type ='edit')
    field_id = TemplateField.try(:find_by, {name: field_name}).try(:id)
    false if field_id.nil?
    if FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).nil?
      false
    else
      if type == 'view'
        roles = FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).view_permission.try(:split, ",")
      else
        roles =  FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).edit_permission.try(:split, ",")
      end
      if roles.nil?
        true
      else
        !roles.include?(role.to_s)
      end
    end
  end
  def is_field_hidden(field_name, role, type ='view')
    field_id = TemplateField.try(:find_by, {name: field_name}).try(:id)
    false if field_id.nil?
    if FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).nil?
      false
    else
      if type == 'view'
        roles = FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).view_permission.try(:split, ",")
      else
        roles =  FieldAccessControl.find_by(template_field_id: field_id, organization_id: self.id).edit_permission.try(:split, ",")
      end
      if roles.nil?
        true
      else
        !roles.include?(role.to_s)
      end
    end
  end
end

app/controllers/api/v1/organizations_controller.rb
class Api::V1::OrganizationsController < Api::V1::BaseController
  version 1

  skip_after_action :verify_authorized, only: [:index]
  after_action :verify_policy_scoped, only: [:index]

  def index
    expose policy_scope(Organization)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController

  def show
    authorize @organization
    @members = @organization.users.invitation_accepted
  end

  def update
    authorize @organization
    @organization.update(organization_params)
    if params[:organization][:users_attributes]
      redirect_to organization_members_path(@organization), notice: "Members updated"
    else
      redirect_to @organization, notice: "Organization updated"
    end
  end

  private

  def organization_params
    whitelisted = params.require(:organization).permit(
      :trade_name,
      :street_address,
      :city,
      :email,
      :state,
      :zipcode,
      :call_to_action,
      :sale_sheet_phone,

      :toll_free,
      :main,
      :sales,
      :mobile_phone,
      :service,
      :parts,
      :commentary,
      :warranty,
      :location,
      :sale_term_conditions,
      :term_guidelines,
      :company_logo,
      :map_image,
      :users_attributes => [
        :id,
        :_destroy,
        :memberships_attributes => [:id, :role_id, :active, :_destroy]
      ]
    )
    whitelisted[:setting] = params[:organization][:setting].permit! if params[:organization][:setting]
    whitelisted
  end
end

app/views/admin/organizations/_appraisal_templates.html.haml
- appraisal_templates = f.object.appraisal_templates.map(&:id)
%br
%h3 Appraisal Templates
%table.index_table.datatable
  %thead
    %tr
      %th
      %th ID
      %th Name
      %th Label
      %th Agent
  %tbody
    - AppraisalTemplate.all.each do |appraisal_template|
      %tr
        %td
          = check_box_tag 'organization[appraisal_template_ids][]', appraisal_template.id, appraisal_templates.include?(appraisal_template.id)
        %td= appraisal_template.id
        %td= appraisal_template.name
        %td= appraisal_template.label
        %td= appraisal_template.agent? ? "Yes" : "No"

app/views/admin/organizations/_appraisal_templates_view.html.haml
%br
%h3 Appraisal Templates
%table.index_table.datatable
  %thead
    %tr
      %th{:style => "display:none"}
      %th ID
      %th Name
      %th Label
      %th Agent
  %tbody
    - organization.appraisal_templates.each do |appraisal_template|
      %tr
        %td{:style => "display:none"}
        %td= appraisal_template.id
        %td= appraisal_template.name
        %td= appraisal_template.label
        %td= appraisal_template.agent? ? "Yes" : "No"

app/views/admin/organizations/_fields_with_control.html.haml
- template_field_ids = TemplateField.has_access_control.map(&:id)
- organization_field_ids = organization_fields.map(&:id)
- existing_roles_view = FieldAccessControl.where(organization_id: f.object.id).try(:pluck,:template_field_id, :view_permission)
- existing_roles_edit = FieldAccessControl.where(organization_id: f.object.id).try(:pluck,:template_field_id, :edit_permission)
- existing_roles_view = Hash[existing_roles_view.map{|u|[u[0], u[1]]}]
- existing_roles_edit = Hash[existing_roles_edit.map{|u|[u[0], u[1]]}]
%br
%h3 Template Fields
%table.index_table.datatable
  %thead
    %tr
      %th Field ID
      %th Name
      %th View
      %th Edit
  %tbody
    - TemplateField.has_access_control.each do |template_field|

      %tr
        %td= template_field.name
        %td= template_field.label
        %td
          = select_tag "view_permission[#{template_field.id}]", options_for_select(Role.staff.collect {|r| ["#{r.name} - #{r.profile}", r.id]}, existing_roles_view[template_field.id].try(:split, ",") || []), multiple: true
        %td
          = select_tag "edit_permission[#{template_field.id}]", options_for_select(Role.staff.collect {|r| ["#{r.name} - #{r.profile}", r.id]}, existing_roles_edit[template_field.id].try(:split, ",") || []), multiple: true

app/views/admin/organizations/_users.html.haml
- user_ids = f.object.users.map(&:id)
%br
%h3 Users
%table.index_table.datatable
  %thead
    %tr
      %th
      %th ID
      %th First Name
      %th Last Name
      %th Email
      %th Role
  %tbody
    - User.all.each do |user|
      %tr
        %td
          = check_box_tag 'organization[user_ids][]', user.id, user_ids.include?(user.id)
        %td= user.id
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= Membership.get_role(f.object, user).try(:profile_name)
%i This section selects the users who are a member of the organization in any capacity.  By default they are a Rep.  To alter the user's role, visit the memberships page.

app/views/admin/organizations/_users_view.html.haml
%br
%h3 Users
%table.index_table.datatable
  %thead
    %tr
      %th{:style => "display:none"}
      %th ID
      %th First Name
      %th Last Name
      %th Email
      %th Role
  %tbody
    - organization.users.each do |user|
      %tr
        %td{:style => "display:none"}
        %td= user.id
        %td= user.first_name
        %td= user.last_name
        %td= user.email
        %td= Membership.get_role(organization, user).try(:profile_name)