config/routes.rb
Rails.application.routes.draw do
  resources :checklists do
    resources :checklist_items do
      member do
        post :completed
        post :uncompleted
      end
    end
  end
  resources :valuation_url_comments

  get 'members/index'

  ActiveAdmin.routes(self)

  devise_for :users, controllers: { sessions: 'sessions' }

  root to: "pages#home"

  resources :pre_launch_registrations, only: [:new, :create] do
    get :success, on: :collection
  end

  resources :organizations, only: [:show, :edit, :update] do
    resources :customers, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :bulk_archive, on: :collection
    end

    resources :appraisals, except: :destroy do
      get :archived, on: :collection
      put :archive, on: :member
      put :clone, on: :member
      get :sales_sheet, on: :member
      get :appraisal_sheet, on: :member
      put :bulk_archive, on: :collection
      get :remove_entry, on: :member
      get :history, on: :member
      post :comment, on: :member
      get :valuations, on: :member
      post :pin, on: :member
      post :unpin, on: :member
      get :reveal_comments, on: :member
      get :hide_comments, on: :member
      put :valuation, on: :member

      resources :discussions do
        resources :discussion_comments
      end

      resources :valuation_urls
    end

    resources :members, only: [:index, :show, :update] do
      post :invite_user, on: :collection
      get :reset_password, on: :member
      get :resend_invitation, on: :member
    end
  end

  resources :members, only: [] do
    get :accept_invitation, on: :collection
  end

  resources :attachments

  resources :reports do
    get :inventory_commitments, on: :collection
  end

  resources :print_templates

  resources :appraisal_categories, only: [:show]

  namespace :api do
    api version: 1, module: 'v1' do
      resources :sessions, only: [:create]

      resources :appraisals, only: [:index] do
        resources :appraisal_categories, only: [:show]
      end

      resources :organizations, only: [:index] do
        resources :appraisals, only: [:create, :show, :update]
        resources :customers, only: [:create, :show, :update]
      end
    end
  end
end

app/models/checklist_item.rb
class ChecklistItem < ActiveRecord::Base
  belongs_to :checklist

  validates :description, presence: true
end

app/controllers/checklist_items_controller.rb
class ChecklistItemsController < ApplicationController
  #before_action :find_checklist

  def new
    @check_list_item = ChecklistItem
      .new(checklist_id: params[:checklist_id], creator_id: current_user.id)
    authorize @check_list_item
  end

  def create
    @check_list_item = ChecklistItem
      .create(description: check_list_item_params[:description], checklist_id: params[:checklist_id])
    authorize @check_list_item
  end

  def edit
    @check_list_item = ChecklistItem.find(params[:id])
    authorize @check_list_item
  end

  def update
    @check_list_item = ChecklistItem.find(params[:id])
    @check_list_item.update_attributes(check_list_item_params)

    authorize @check_list_item
  end

  def destroy
    @check_list_item = ChecklistItem.find(params[:id])
    @check_list_item.destroy

    authorize @check_list_item
  end

  def completed
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.update_attributes(completed: true, completed_at: DateTime.now)

    render json: { status: 200 }
    authorize @checklist_item
  end

  def uncompleted
    @checklist_item = ChecklistItem.find(params[:id])
    @checklist_item.update_attributes(completed: false, completed_at: nil)

    render json: { status: 200 }
    authorize @checklist_item
  end

  def check_list_item_params
    params
      .require(:checklist_item)
      .permit(:description, :checklist_id)
  end
end

app/views/checklist_items/_check_list_item.html.haml
.checklist-item-container
  .checklist-item-hover
    = link_to checklist_checklist_item_path(check_list_item.checklist.id, check_list_item.id), remote: true, method: :delete do
      = fa_icon "trash"
    = link_to "Edit", edit_checklist_checklist_item_path(check_list_item.checklist.id, check_list_item.id), remote: true


  %li.checklist-item(id="checklist-item-#{check_list_item.id}")
    = check_box_tag "checklist", 1, check_list_item.completed?, data: { behavior: "#{check_list_item.completed? ? "check-list-item-uncompleted" : "check-list-item-completed"}", "check-list-id" => check_list_item.checklist.id, "check-list-item-id" => check_list_item.id }
    = check_list_item.description

app/views/checklist_items/_check_list_item_edit_form.html.haml
= simple_form_for check_list_item, remote: true,
                  url: checklist_checklist_item_path(checklist_id: check_list_item.checklist.id, format: :js) do |f|
  = f.input :description, label: "Description"

  .center-text
    = f.submit nil, class: "btn btn-primary",
             data: { disable_with: "Submitting ..." }

app/views/checklist_items/_check_list_item_edit_modal.html.haml
.modal#check-list-item-creation-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: { dismiss: "modal" }} &times;
        %h4.modal-title Add a Checklist item
      .modal-body
        = render "check_list_item_edit_form", check_list_item: @check_list_item

app/views/checklist_items/_check_list_item_form.html.haml
= simple_form_for check_list_item, remote: true,
                  url: checklist_checklist_items_path(checklist_id: check_list_item.checklist.id, format: :js) do |f|
  = f.input :description, label: "Description"

  .center-text
    = f.submit nil, class: "btn btn-primary",
             data: { disable_with: "Submitting ..." }

app/views/checklist_items/_check_list_item_modal.html.haml
.modal#check-list-item-creation-modal
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{data: { dismiss: "modal" }} &times;
        %h4.modal-title Add a Checklist item
      .modal-body
        = render "check_list_item_form", check_list_item: @check_list_item

app/views/checklist_items/create.js.erb
$modal = $("#check-list-item-creation-modal");

<% if @check_list_item.persisted? %>
  $modal.modal("hide");

  $div = $("#check-list-<%= @check_list_item.checklist.id %> .checklist-item-add-btn");
  $checklist_item = $("<%= j render "check_list_item", check_list_item: @check_list_item %>");

  $div.before($checklist_item);
<% else %>
  form = "<%= j render "check_list_item_form", check_list_item: @check_list_item %>";
  $modal.find(".modal-body").html(form);
<% end %>

app/views/checklist_items/destroy.js.erb
$("#checklist-item-<%= @check_list_item.id %>").parent().fadeOut().remove()

app/views/checklist_items/edit.js.erb
$modal = $("<%= j render 'check_list_item_edit_modal', check_list_item: @check_list_item %>");

if ($("#check-list-item-creation-modal").length > 0) {
  $("#check-list-item-creation-modal").remove()
}

$("body").append($modal);

$('#check-list-item-creation-modal').modal();

app/views/checklist_items/new.js.erb
$modal = $("<%= j render 'check_list_item_modal' %>");

if ($("#check-list-item-creation-modal").length > 0) {
  $("#check-list-item-creation-modal").remove()
}

$("body").append($modal);

$('#check-list-item-creation-modal').modal();

app/views/checklist_items/update.js.erb
$modal = $("#check-list-item-creation-modal");

<% if @check_list_item.persisted? %>
  $modal.modal("hide");

  $checklist_item = $("<%= j render "check_list_item", check_list_item: @check_list_item %>");

  $("#checklist-item-<%= "#{@check_list_item.id}" %>").parent().replaceWith($checklist_item)
<% else %>
  form = "<%= j render "check_list_item_edit_form", check_list_item: @check_list_item %>";
  $modal.find(".modal-body").html(form);
<% end %>